name: srbench
channels:
    - conda-forge
dependencies:
    - make
    - compilers
    - python=3.8
    - cmake=3.19.1 # operon, feat
    - eigen=3.4.0 # operon, feat, ellyn
    - scikit-learn=0.24.1 
    - pyarrow
    - python-devtools=0.9.0
    - swig=4.0.2
    - pandas 
    - numpy
    - jupyter
    - pytest
    - matplotlib
    # pip
    - pip=20.3.3 
    - pip:
        - pmlb==1.0.1.post3
        - eigency==1.77
        - sympy==1.11.1
        - pandas
        - setuptools
        - torch==1.12.1
        - functorch==0.2.1
        - sympytorch==0.1.1
